### ISSUE TITLE
[Question] Is there a way to know when the file is saved or the tab/editor is closed?

### ISSUE THREAD

**Issue by kud** [sindresorhus/open-editor#10]
For some reasons, I use `subl -n -w` to keep it in the buffer and know when the user stopped to edit the file.

Is there a way to have a callback with your lib?

Thanks.

**Comment by sindresorhus** [comment]
Not currently. From the readme:

> It does not wait for the editor to start or quit.

It could potentially special-handle Sublime, since `subl` supports this, but when opening apps normally with `$ open`, you can only wait for the app to close. You don't know when a tab or file closes.

**Comment by kud** [comment]
I see. Thank you :)
