### ISSUE TITLE
Find out if it worked

### ISSUE THREAD

**Issue by peterbe** [sindresorhus/open-editor#12]
If I have a typo (e.g. `export EDITOR=cude`) or I supply some spec that fails horribly it would be nice to know if it worked. E.g. 

```javascript
if (openEditor(['unicorn.js:5:3'])) {
  console.log('Editor opening working');
} else {
  console.warn('Editor opening failed');
}
```
Even better if it could be `try { } catch ` instead of a boolean return.

**Comment by sindresorhus** [comment]
The `openEditor` method would have to be made async and awaited then. We would also have to use `Promise.all` here: https://github.com/sindresorhus/open-editor/blob/9c7afcb955fb92da1a5825694ddfcdfe01f816f9/index.js#L70-L72 and properly await it. I don't mind changing it if someone does a good pull request.
